version: '3.4'

services:
  fileloader:
    image: fileloader
    build:
      context: node_modules/file-loader
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
